services:
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - micro-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  contact-service:
    image: contact-service:latest
    build: ./contact_service
    container_name: contact-service
    ports:
      - "9002:9002"
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - micro-net

  user-service:
    image: user-service:latest
    build: ./user_service
    container_name: user-service
    ports:
      - "9001:9001"
    depends_on:
      contact-service:
        condition: service_started
      discovery-server:
        condition: service_healthy
    networks:
      - micro-net

  postgres-auth:
    image: postgres:16
    container_name: postgres-auth
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - micro-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    image: auth-service:latest
    build: ./auth-service
    container_name: auth-service
    ports:
      - "9000:9000"
    depends_on:
      postgres-auth:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - micro-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - micro-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - micro-net

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      user-service:
        condition: service_started
      contact-service:
        condition: service_started
      auth-service:
        condition: service_started
      discovery-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - micro-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      user-service:
        condition: service_started
      contact-service:
        condition: service_started
    networks:
      - micro-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - micro-net

networks:
  micro-net:
    external: true

volumes:
  postgres_data:
