server:
  port: 9002
info:
  app:
    name: Contact Service
    description: Manages and serves user contact information
    version: 1.0.0
    owner: Backend Team
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name}, traceId=%X{traceId}, spanId=%X{spanId}]"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka

spring:
  application:
    name: contact-service